org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at java.base@16.0.1/java.lang.String.split(String.java:2326)
	at java.base@16.0.1/java.lang.String.split(String.java:2399)
	at app//code.GeneralSearch.getPossibleActions(GeneralSearch.java:712)
	at app//code.GeneralSearch.generalSearch(GeneralSearch.java:353)
	at app//code.Matrix.solve(Matrix.java:302)
	at app//tests.TestMatrixPublic.testd3(TestMatrixPublic.java:351)
	at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@16.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base@16.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@16.0.1/java.lang.reflect.Method.invoke(Method.java:567)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base@16.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@16.0.1/java.lang.Thread.run(Thread.java:831)

